---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-api-celery
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: workflow-api-celery
      app.kubernetes.io/component: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: workflow-api-celery
        app.kubernetes.io/component: api
    spec:
      containers:
      - name: workflow-api-celery
        image: "{{ .Values.global.registry_url }}/workflow-api:{{ .Values.global.kaapana_build_version  }}"
        imagePullPolicy:  {{ .Values.global.pull_policy_images }}
        env:
        - name: DATABASE_URL
          value: "postgresql://{{ .Values.kaapana_database.postgres_user}}:{{ .Values.kaapana_database.postgres_password}}@{{ .Values.kaapana_database.appName | default .Chart.Name }}-database-service.{{ .Values.global.services_namespace }}.svc:5432"
        - name: CELERY_BROKER_URL
          value: "redis://workflow-api-redis-service.{{ .Values.global.services_namespace }}.svc:6379/0"
        - name: AIRFLOW_URL
          value: "http://airflow-webserver-service.{{  .Values.global.services_namespace  }}.svc:8080/flow/kaapana/api" #change this to airflow API endpoint
        - name: CELERYD_CONCURRENCY
          value: "2"
        command: ["celery"]
        args: ["-A", "app.adapters.config.celery_app", "worker", "--loglevel=info"]
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "256Mi"
        volumeMounts:
        - name: tmp
          mountPath: "/tmp"
        securityContext:
           allowPrivilegeEscalation: false
           readOnlyRootFilesystem: true  
      volumes:
      - name: tmp
        emptyDir: {}
      imagePullSecrets:
        - name: registry-secret
