---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-api
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: workflow-api
      app.kubernetes.io/component: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: workflow-api
        app.kubernetes.io/component: api
    spec:
      initContainers:
          - name: init-workflow-api
            image: "{{ .Values.global.registry_url }}/service-checker:{{ .Values.global.kaapana_build_version }}"
            imagePullPolicy:  {{ .Values.global.pull_policy_images }}
            env:
              - name: WAIT
                value: "{{ .Values.kaapana_database.appName | default .Chart.Name }}-database-,{{ .Values.kaapana_database.appName | default .Chart.Name }}-database-service.{{  .Values.global.services_namespace  }}.svc,5432"
              - name: DELAY
                value: "2"
              - name: TIMEOUT
                value: "10"
      containers:
      - name: workflow-api
        image: "{{ .Values.global.registry_url }}/workflow-api:{{ .Values.global.kaapana_build_version  }}"
        imagePullPolicy:  {{ .Values.global.pull_policy_images }}
        env:
        - name: APPLICATION_ROOT
          value: /workflow-api
        - name: PORT
          value: "8080"
        - name: WORKERS
          value: "4"
        - name: LOG_LEVEL
          value: INFO
        - name: DATABASE_URL
          value: "postgresql+asyncpg://{{ .Values.kaapana_database.postgres_user}}:{{ .Values.kaapana_database.postgres_password}}@{{ .Values.kaapana_database.appName | default .Chart.Name }}-database-service.{{ .Values.global.services_namespace }}.svc:5432"
        - name: ACCESS_INFORMATION_INTERFACE_URL
          value: "http://aii-service.{{  .Values.global.services_namespace  }}.svc:8080"
{{- if .Values.airflow.enabled }}
        # Airflow adapter config
        - name: AIRFLOW_API_URL
          value: {{ .Values.airflow.api_url_base }}.{{ .Values.global.services_namespace }}.svc:{{ .Values.airflow.api_port }}{{ .Values.airflow.api_endpoint }}
        - name: AIRFLOW_DAG_FOLDER
          value: {{ .Values.airflow.dag_folder }}
{{- end }}
{{- if .Values.global.dev_files }}
        - name: DEV_FILES
          value: "True"
{{- end }}
        volumeMounts:
{{- if .Values.airflow.enabled }}
        # Airflow volume mount
        - name: airflow-dags-pvc
          mountPath: /kaapana/mounted/workflows/dags
{{- end }}
{{- if .Values.global.dev_files }}
        - name: workflow-api-dev
          mountPath: /app
{{- end }}
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: "1024Mi"
          requests:
            memory: "100Mi"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true     
      volumes:
{{- if .Values.airflow.enabled }}
      # Airflow volume definition
      - name: airflow-dags-pvc
        persistentVolumeClaim:
          claimName: {{ .Values.airflow.scheduler_claim_name }} # must match the PVC created in the airflow chart
{{- end }}
{{- if .Values.global.dev_files }}
      - name: workflow-api-dev
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-dev-pv-claim
{{- end }}
      imagePullSecrets:
        - name: registry-secret
