---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-api
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: workflow-api
      app.kubernetes.io/component: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: workflow-api
        app.kubernetes.io/component: api
    spec:
      initContainers:
          - name: init-workflow-api
            image: "{{ .Values.global.registry_url }}/service-checker:{{ .Values.global.kaapana_build_version }}"
            imagePullPolicy:  {{ .Values.global.pull_policy_images }}
            env:
              - name: WAIT
                value: "{{ .Values.kaapana_database.appName | default .Chart.Name }}-database-,{{ .Values.kaapana_database.appName | default .Chart.Name }}-database-service.{{  .Values.global.services_namespace  }}.svc,5432"
              - name: DELAY
                value: "2"
              - name: TIMEOUT
                value: "10"
      containers:
      - name: workflow-api
        image: "{{ .Values.global.registry_url }}/workflow-api:{{ .Values.global.kaapana_build_version  }}"
        imagePullPolicy:  {{ .Values.global.pull_policy_images }}
        env:
        - name: APPLICATION_ROOT
          value: "/workflow-api"
        - name: DATABASE_URL
          "postgresql://{{ .Values.kaapana_database.postgres_user}}:{{ .Values.kaapana_database.postgres_password}}@{{ .Values.kaapana_database.appName | default .Chart.Name }}-database-service.{{ .Values.global.services_namespace }}.svc:5432"
        - name: AII_URL
          value: "http://aii-service.{{ .Values.global.services_namespace }}.svc:8080"
        - name: CELERY_BROKER_URL
          value: "redis://workflow-api-redis-service.{{ .Values.global.services_namespace }}.svc:6379/0"
        - name: DEV_FILES
          value: "True"
        - name: AIRFLOW_URL
          value: "http://airflow-webserver-service.{{  .Values.global.services_namespace  }}.svc:8080/flow/kaapana/api"
        volumeMounts:   
        - name: workflow-api-dev
          mountPath: /app
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "100Mi"
        #securityContext:
        #  allowPrivilegeEscalation: false
         # readOnlyRootFilesystem: true     
      volumes:
      - name: workflow-api-dev
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-dev-pv-claim
      imagePullSecrets:
        - name: registry-secret
