version: "3.9"
services:
  postgres:
    image: "docker.io/postgres:17.7-alpine"
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kaapanauser
      - POSTGRES_PASSWORD=kaapanapassword
      - POSTGRES_DB=kaapanauser
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kaapanauser"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data

  api:
    build:
      context: .
    image: workflow-api:latest
    ports:
      - 8080:8080
    environment:
      - APPLICATION_ROOT=/
      - DATABASE_URL=postgresql://kaapanauser:kaapanapassword@postgres:5432/kaapanauser
      - DEV_FILES=True
      - PORT=8080
      - ENABLE_TEST_ADAPTER=true
      - WORKERS=4
      - LOG_LEVEL=INFO
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./files:/app

volumes:
  database:
