---
global:
    image: "dag-total-segmentator"
    action: "copy"

extension_params:
    task_ids: 
        definition: "Multi-selectable nnunet versions used in different tasks"
        type: "list_multi"
        value: [
            "Task251_TotalSegmentator_part1_organs_1139subj",
            "Task252_TotalSegmentator_part2_vertebrae_1139subj",
            "Task253_TotalSegmentator_part3_cardiac_1139subj",
            "Task254_TotalSegmentator_part4_muscles_1139subj",
            "Task255_TotalSegmentator_part5_ribs_1139subj",
            "Task256_TotalSegmentator_3mm_1139subj",
            "Task258_lung_vessels_248subj",
            "Task150_icb_v0",
            "Task260_hip_implant_71subj",
            "Task269_Body_extrem_6mm_1200subj",
            "Task503_cardiac_motion",
            "Task273_Body_extrem_1259subj",
            "Task315_thoraxCT",
        ]
        default: [
            "Task251_TotalSegmentator_part1_organs_1139subj",
            "Task252_TotalSegmentator_part2_vertebrae_1139subj",
            "Task253_TotalSegmentator_part3_cardiac_1139subj",
            "Task254_TotalSegmentator_part4_muscles_1139subj",
            "Task255_TotalSegmentator_part5_ribs_1139subj",
            "Task256_TotalSegmentator_3mm_1139subj",
            "Task258_lung_vessels_248subj",
            "Task150_icb_v0",
            "Task260_hip_implant_71subj",
            "Task269_Body_extrem_6mm_1200subj",
            "Task273_Body_extrem_1259subj",
        ]
