{{- $uuid := uuidv4 | trunc 10 }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mitk-flow-{{ $uuid }}
  namespace: {{ .Values.global.base_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: mitk-flow-{{ $uuid }}
  template:
    metadata:
      labels:
        app-name: mitk-flow-{{ $uuid }}
    spec:
      restartPolicy: Always
      containers:
        # ToDo add init-container to wait for db-host
      - name: mitk
        image: {{  .Values.global.registry_url }}{{  .Values.global.registry_project }}/mitk-flow:1.0-vdev
        imagePullPolicy: {{ .Values.global.pull_policy_pods }}
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "1Gi"
        env:
        - name: INGRESS_PATH
          value: mitk-flow-{{ $uuid }}
        - name: USER
          value: mitk
        - name: PASSWORD
          value: mitk
        - name: WORKFLOW_DIR
          value: {{ .Values.workflow_dir }}
        - name: BATCH_NAME
          value: {{ .Values.batch_name }}
        - name: OPERATOR_OUT_DIR
          value: {{ .Values.operator_out_dir }} 
        - name: OPERATOR_IN_DIR
          value: {{ .Values.operator_in_dir }}           
        volumeMounts:
        - name: mitk-data
          mountPath: /data
      volumes:
      - name: mitk-data
        hostPath:
          path: "{{ .Values.mount_path }}"
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: registry-secret
---
kind: Service
apiVersion: v1
metadata:
  name: mitk-flow-{{ $uuid }}
  namespace: {{ .Values.global.base_namespace }}
  labels:
    app: mitk-flow-{{ $uuid }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: pt-mitk-http
  type: ClusterIP
  selector:
    app-name: mitk-flow-{{ $uuid }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: mitk-flow-{{ $uuid }}-redirect
  namespace: {{ .Values.global.base_namespace }}
spec:
  redirectRegex:
    regex: ^.*/mitk-flow-{{ $uuid }}([^\/]*)$
    replacement: /mitk-flow-{{ $uuid }}/
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mitk-flow-{{ $uuid }}
  namespace: {{ .Values.global.base_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd,{{ .Values.global.base_namespace }}-mitk-flow-{{ $uuid }}-redirect@kubernetescrd,kube-system-strip-prefix@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /mitk-flow-{{ $uuid }}
        backend:
          serviceName: mitk-flow-{{ $uuid }}
          servicePort: pt-mitk-http
---
