---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: kube-system
  labels:
    app-name: keycloak
spec:
  selector:
    app-name: keycloak
{{- if .Values.global.dev_ports }}
  type: NodePort
  ports:
  - name: kc-http-port
    port: 80
    targetPort: http
    nodePort: 3080
    protocol: TCP
  - name: kc-https-port
    port: 443
    targetPort: https
    nodePort: 3443
    protocol: TCP
  - name: kc-admin-port
    port: 9090
    targetPort: admin
    nodePort: 3090
    protocol: TCP
{{- else }}
  type: ClusterIP
  ports:
  - name: kc-http-port
    port: 80
    targetPort: http
    protocol: TCP
  - name: kc-https-port
    port: 443
    targetPort: https
    protocol: TCP
  - name: kc-admin-port
    port: 9090
    targetPort: admin
    protocol: TCP
{{- end }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: keycloak-ingress-ip
  namespace: kube-system
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /auth
        backend:
          serviceName: keycloak-service
          servicePort: kc-http-port
---