---
{{- $uuid := uuidv4 | trunc 10 }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pysyft-nb-{{ $uuid }}
  namespace: {{ .Values.global.base_namespace }}
  labels:
    k8s-app: pysyft-nb-{{ $uuid }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: pysyft-nb-{{ $uuid }}
  template:
    metadata:
      labels:
        app-name: pysyft-nb-{{ $uuid }}
    spec:
      containers:
      - name: pysyft-nb-{{ $uuid }}
        image: {{ .Values.global.registry_url }}{{ .Values.global.registry_project }}/openmined:0.1.0-vdev
        imagePullPolicy: {{ .Values.global.pull_policy_pods }}
        # memory space
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "1Gi"
        ports:
        - name: pysyft-nb-http
          containerPort: 8888
        env:
        - name: INGRESS_PATH
          value: "/pysyft-nb-{{ $uuid }}"
        volumeMounts:
          - name: pysyftdata
            mountPath: /appdata
      volumes:
      - name: pysyftdata
        hostPath:
          {{- if .Values.mount_path }}
          path: {{ .Values.mount_path }}
          {{- else }}
          path: {{ .Values.global.slow_data_dir }}/minio
          {{- end }}
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: registry-secret
---
kind: Service
apiVersion: v1
metadata:
  name: pysyft-nb-{{ $uuid }}
  namespace: {{ .Values.global.base_namespace }}
spec:
  selector:
    app-name: pysyft-nb-{{ $uuid }}
  ports:
    - protocol: TCP
      port: 8888
      targetPort: pysyft-nb-http
      name: log-http-port
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pysyft-nb-{{ $uuid }}
  namespace: {{ .Values.global.base_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd
    traefik.ingress.kubernetes.io/preserve-host: "true"
    #traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: 
    http:
      paths:
      - path: "/pysyft-nb-{{ $uuid }}"
        backend:
          serviceName: pysyft-nb-{{ $uuid }}
          servicePort: log-http-port