---
apiVersion: v1
data:
  Launcher.properties: |
    mx = 2048
    ms = 1024
    add = -XX:+ExitOnOutOfMemoryError -XX:+CrashOnOutOfMemoryError
  config.xml: |+
    <Configuration>
        <Server
            maxThreads="12"
            port="1050"/>
        <Pipeline name="Pipeline">
            <DicomImportService
                calledAETTag="00120020"
                callingAETTag="00120010"
                class="org.rsna.ctp.stdstages.DicomImportService"
                logConnections="rejected"
                name="DicomImportService"
                port="11112"
                quarantine="/data/incoming/.quarantines/DicomImportService"
                root="/data/incoming/.roots/DicomImportService"/>
        <KaapanaDagTrigger
            class="org.rsna.ctp.dkfz.KaapanaDagTrigger"
            condition_tag="0008103E"
            dagnames="service-process-incoming-dcm"
            debug_log="no"
            airflowUrl="http://airflow-service.flow.svc:8080/flow"
            triggerurl="/kaapana/api/trigger"
            name="MetaExtraction"
            acceptDuplicates="yes"
            defaultString=""
            logDuplicates="no"
            quarantine="/data/incoming/.quarantines/KaapanaDagTrigger"
            root="/data/incoming"
            setStandardExtensions="yes"
            structure="(0020,000E)"
            unchangedCounter = "2"
            limitTriggerOnRunningDagsUrl="service-extract-metadata service-process-incoming-dcm"
            dagRunUrl="/api/experimental/dags/%s/dag_runs?state=running"
            runningDagLimits="150"
            whitespaceReplacement="_"/>
        </Pipeline>
        <Pipeline name="DicomSTOWRSImportService">
            <HttpImportService
                name="DicomSTOWRSLocalImportService"
                id="DicomSTOWRSLocalImportService"
                class="org.rsna.ctp.stdstages.DicomSTOWRSImportService"
                port="7777"
                ssl="no"
                requireAuthentication="no"
                logConnections="no"
                logDuplicates="no"
                quarantine="/data/incoming/.quarantines/HttpImportService"
                root="/data/incoming/.roots/HttpImportService"/>
        <KaapanaDagTrigger
            class="org.rsna.ctp.dkfz.KaapanaDagTrigger"
            condition_tag="0008103E"
            dagnames="service-process-incoming-dcm"
            debug_log="no"
            airflowUrl="http://airflow-service.flow.svc:8080/flow"
            triggerurl="/kaapana/api/trigger"
            name="MetaExtraction"
            acceptDuplicates="yes"
            defaultString=""
            logDuplicates="no"
            quarantine="/data/incoming/.quarantines/KaapanaDagTrigger"
            root="/data/incoming"
            setStandardExtensions="yes"
            structure="(0020,000E)"
            unchangedCounter = "2"
            limitTriggerOnRunningDagsUrl="service-extract-metadata service-process-incoming-dcm"
            dagRunUrl="/api/experimental/dags/%s/dag_runs?state=running"
            runningDagLimits="150"
            fix_aetitle="DICOM_WEB"
            whitespaceReplacement="_"/>
        </Pipeline>
    </Configuration>
kind: ConfigMap
metadata:
  name: ctp-config
  namespace: {{ .Values.global.flow_namespace }}


