---
apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak-service
  namespace: "{{  .Values.global.system_namespace  }}"
  labels:
    app-name: postgres-keycloak
spec:
  selector:
    app-name: postgres-keycloak
  ports:
  - name: postgres-keycloak-port
    port: 5432
    targetPort: 5432
    protocol: TCP
