---
global:
  dynamicVolumes:
  - name: kaapana-persistence-mongodb
    storage: 10Gi
  - name: kaapana-persistence-cas
  - name: kaapana-persistence-couchdb
    storage: 10Gi

couchdb:
  user: kaapanauser
  password: kaapanapassword
