kind: Service
apiVersion: v1
metadata:
  name: adminer-service
  namespace: {{ .Values.global.base_namespace }}
spec:
  selector:
    app-name: adminer
  ports:
    - protocol: TCP
      port: 8080
      name: adminer-http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adminer-ingress
  namespace: {{ .Values.global.base_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd
    traefik.ingress.kubernetes.io/preserve-host: "true"
    #traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: 
    http:
      paths:
      - path: "/adminer"
        defaultBackend:
          service.name: adminer-service
          service.port.name: adminer-http
