
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-logging-service
  namespace: {{ .Values.global.monitoring_namespace }}
  labels:
    app-name: kibana-logging
spec:
  selector:
    app-name: kibana-logging
  ports:
  - name: kibana-port
    port: 5601
    targetPort: 5601
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-logging-ingress-ip
  namespace: {{ .Values.global.monitoring_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd,kube-system-strip-prefix@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /logging
        defaultBackend:
          service.name: kibana-logging-service
          service.port.number: 5601
---