---
global:
    pull_policy_pods: "IfNotPresent"
    pull_policy_jobs: "IfNotPresent"
    pull_policy_operators: "IfNotPresent"
    core_namespace: "kube-system"
    base_namespace: "base"
    gpu_support: false
    credentials:
        keycloak_admin_username: "admin"
        keycloak_admin_password: "Kaapana2020"
    dicom_port: "11112"
    http_port: "80"
    https_port: "443"
    auth_node_port: "8000"
    fast_data_dir: /home/kaapana
    slow_data_dir: /home/kaapana
    home_dir: /root
    version: "0.1.0-vdev"
    default_base_requests_mem: "50Mi"
    default_base_limits_mem: "50Mi"
    # default_base_requests_cpu: 0.5
    # default_base_limits_cpu: 1
    default_system_requests_mem: "50Mi"
    default_system_limits_mem: "50Mi"
    # default_system_requests_cpu: 0.5
    # default_system_limits_cpu: 1
    http_proxy: ""
    https_proxy: ""
    kaapana_collections:
        - name: kaapana-base-collection
          version: 0.1.0-vdev
    preinstall_extensions:
        - name: code-server-chart
          version: 3.10.2
---
