offline_mode: 'false'
prefetch_extensions: 'false'
dev_mode: 'true'
container_registry_url:
container_registry_username:
container_registry_password:
fast_data_dir: "/home/kaapana-admin"
slow_data_dir: "/home/kaapana-admin"
http_port: 80
https_port: 443
dicom_port: 11112
admin_namespace: "admin"
helm_namespace: "admin"
services_namespace: "services"
jobs_namespace: "jobs"
extensions_namespace: "extensions"
