admin_namespace: "admin"
helm_namespace: "default"
services_namespace: "services"
extensions_namespace: "extensions"
kaapana_collections:
- name: kaapana-extension-collection
preinstall_extensions:
- name: kaapana-platform-chart
- name: code-server-chart
- name: kaapana-workflows-core

