---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-ui
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: workflow-ui-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: workflow-ui-app
    spec:
      containers:
      - name: workflow-ui-container
        image: "{{ .Values.global.registry_url }}/workflow-ui:{{ .Values.global.kaapana_build_version  }}"
        imagePullPolicy:  "{{ .Values.global.pull_policy_images }}"
        env:
        - name: VITE_WORKFLOW_API_URL
          value: /workflow-api    
{{- if .Values.global.dev_files }}
        - name: DEV_FILES
          value: "True"
        volumeMounts:   
        - name: workflow-ui-dev
          mountPath: /app
{{- end }}
        ports:
        - name: http-port
          containerPort: 80
        resources:
          limits:
            memory: "5Gi"
          requests:
            memory: "100Mi"
        volumeMounts:
          - name: tmp
            mountPath: /var/run
          - name: cache
            mountPath: /var/cache/nginx
        securityContext:
          allowPrivilegeEscalation: false
{{- if .Values.global.dev_files }}
          readOnlyRootFilesystem: false
{{- else }}
          readOnlyRootFilesystem: true
{{- end }}
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}  
{{- if .Values.global.dev_files }}
      - name: workflow-ui-dev
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-dev-pv-claim
{{- end }}
      
      priorityClassName: kaapana-high-priority
      imagePullSecrets:
        - name: registry-secret
---