---
apiVersion: v1
kind: Service
metadata:
  name: error-pages-service
  namespace: "{{  .Values.global.admin_namespace  }}"
spec:
  selector:
    app-name: error-pages
  ports:
    - port: 5000
      name: error-http
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ep-strip-prefix
  namespace: "{{  .Values.global.admin_namespace  }}"
spec:
  stripPrefix:
    prefixes:
    - /error-pages
    forceSlash: true
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: error-pages-ingress-ip
  namespace: "{{  .Values.global.admin_namespace  }}"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: {{  .Values.global.admin_namespace  }}-auth-check@kubernetescrd,{{  .Values.global.admin_namespace  }}-ep-strip-prefix@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host: error-pages
    http:
      paths:
      - path:
        pathType: ImplementationSpecific
        backend:
          service:
            name: error-pages-service
            port:
              name: error-http
  - host: 
    http:
      paths:
      - path: /error-pages
        pathType: ImplementationSpecific
        backend:
          service:
            name: error-pages-service
            port:
              name: error-http
---
