---
apiVersion: v1
kind: Service
metadata:
  name: airflow-service
  namespace: {{ .Values.global.flow_namespace }}
spec:
  selector:
    app-name: airflow
  ports:
    - port: 8080
      name: airflow-http
    - port: 5678
      name: debug-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflow-ingress-ip
  namespace: {{ .Values.global.flow_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /flow
        defaultBackend:
          service.name: airflow-service
          service.port.name: airflow-http
---
