apiVersion: v1
kind: Service
metadata:
  namespace: stackrox
  name: "{{ .Values.service_name }}"
spec:
  type: NodePort
  ports:
    - name: "stackrox-dashboard"
      port: 80
      targetPort: 8080
      nodePort: 19080
    - name: "stackrox-dashboard-443"
      port: 443
      targetPort: 8443
      nodePort: 19443
  selector:
    app: central
---