---
dependencies:
  - name: adminer-chart
    version: 4.7.8
    repository: file://../../../../../../services/applications/adminer/adminer-chart
  - name: code-server-chart
    version: 4.2.0
    repository: file://../../../../../../services/applications/code-server/code-server-chart
  - name: doccano
    version: 0.1.0
    repository: file://../../../../../../services/applications/doccano/doccano-charts
  - name: debug-container-chart
    version: 1.0.1
    repository: file://../../../../../../services/applications/debug-container/debug-container-chart
  - name: kaapana-plugin-chart
    version: "0.1.1"
    repository: file://../../../../../../workflows/dag-installer/kaapana-plugin/kaapana-plugin-chart
  - name: jupyterlab-chart
    version: 3.1.1
    repository: file://../../../../../../services/applications/jupyterlab/jupyterlab-chart
  - name: mitk-flow-chart
    version: "2021.02"
    repository: file://../../../../../../services/applications/mitk-flow/mitk-flow-chart
  - name: mitk-flow-workflow
    version: "2021-01-19"
    repository: file://../../../../../../workflows/dag-installer/mitk-flow/mitk-flow-workflow
  - name: mitk-workbench-chart
    version: "2021.02"
    repository: file://../../../../../../services/applications/mitk-workbench/mitk-workbench-chart
  - name: nnunet-workflow
    version: 04-21
    repository: file://../../../../../../workflows/dag-installer/nnunet/nnunet-workflow
  - name: bodypartregression-workflow
    version: 0.1.0
    repository: file://../../../../../../workflows/dag-installer/bodypartregression/bodypartregression-workflow
  - name: radiomics-workflow
    version: 0.1.1
    repository: file://../../../../../../workflows/dag-installer/radiomics/radiomics-workflow
  - name: shapemodel-workflow
    version: 0.1.1
    repository: file://../../../../../../workflows/dag-installer/shapemodel/shapemodel-workflow
  - name: tensorboard-chart
    version: 2.5.0
    repository: file://../../../../../../services/applications/tensorboard/tensorboard-chart
  - name: fastapi-backend-chart
    version: 0.1.0
    repository: file://../../../../../../services/base/fastapi-backend/fastapi-backend-chart
  - name: tfda-execution-orchestrator-workflow
    version: 0.0.1
    repository: file://../../../../../../workflows/dag-installer/tfda-execution-orchestrator/tfda-execution-orchestrator-workflow