project_name: starter-platform-chart
project_abbr: sp
default_version: 0.1.3
offline_mode: 'false'
prefetch_extensions: 'false'
dev_mode: 'true'
container_registry_url:
container_registry_username:
container_registry_password:
fast_data_dir: "/home/kaapana"
slow_data_dir: "/home/kaapana"
http_port: 80
https_port: 443
dicom_port: 11112
auth_node_port: 8000
kaapana_collections:
- name: kaapana-extension-collection
  version: 0.1.0
preinstall_extensions:
- name: code-server-chart
  version: 4.2.0
- name: kaapana-plugin-chart
  version: 0.1.1
additional_env:
- name: INSTANCE_NAME
  default_value: "central"
  helm_path: global.instance_name
