---
global:
  default_jobs_requests_mem: "50Mi"
  default_jobs_limits_mem: "50Mi"
  dynamicVolumes:
  - name: tensorboard
    storage_class: workflow
    storage: 1Gi
  - name: models
    storage_class: workflow
    storage: 100Gi
  - name: workflow-data
    storage_class: workflow
    storage: 100Gi
  - name: mounted-scripts
    storage_class: workflow
    storage: 10Mi

  ### For Local Operators managed by KubernetesExecutor
  - name: dags
    host_path: /workflows/dags
  - name: af-logs
    host_path: /airflow/logs
  - name: af-plugins
    host_path: /workflows/plugins
  - name: uploads
    host_path: /uploads
  - name: ctp-data
    host_path: /ctp/
  - name: dcm4chee-dicom
    host_path: /dcm4che/dicom_data


kaapana_database:
  admin: false
  postgres_user: root
  postgres_password: root
  postgres_db: airflow
  appName: airflow

