services:
  postgres:
    image: "docker.io/postgres:17.2-alpine"
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kaapanauser
      - POSTGRES_PASSWORD=kaapanapassword
      - POSTGRES_DB=kaapanauser
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kaapanauser"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - workflow

  workflow-api:
    build:
      context: ../workflow-api/docker
    image: workflow-api:latest
    ports:
      - 8080:8080
      - "5678:5678" # debugpy
    environment:
      - APPLICATION_ROOT=/
      - PORT=8080
      - WORKERS=4
      - DATABASE_URL=postgresql://kaapanauser:kaapanapassword@postgres:5432/kaapanauser
      - DEV_FILES=True
      - LOG_LEVEL=DEBUG
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../workflow-api/docker/files:/app
    networks:
      - workflow

  workflow-ui:
    build:
      context: ../workflow-ui/docker
    image: workflow-ui:latest
    ports:
      - 5173:80
    environment:
      - VITE_WORKFLOW_API_URL=http://localhost:8080/v1
    volumes:
      - ../workflow-ui/docker/files:/app:cached
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    networks:
      - workflow
    depends_on:
      - workflow-api
volumes:
  database:

networks:
  workflow:
    driver: bridge
