# Dags
apiVersion: v1
kind: PersistentVolume
metadata:
  name: treaefik-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: "1Mi"
{{- if .Values.global.enable_nfs }}
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  nfs:
    server: "10.152.183.15"
    path: "/traefik"
{{- else }}
  storageClassName: host-dir
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.fast_data_dir }}/traefik"
{{- end }}
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: "{{ .Values.global.admin_namespace }}"
    name: treaefik-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: treaefik-pv-claim
  namespace: "{{ .Values.global.admin_namespace }}"
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1Mi"
  volumeName: "treaefik-pv-volume"
---
