---
dependencies:
# MONITORING
  - name: prometheus-chart
    version: "v2.20.1"
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: alertmanager-chart
    version: "v0.21.0"
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: grafana-chart
    version: "6.4.4"
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
  - name: kube-state-metrics-chart
    version: "v1.9.7"
    repository: https://dktk-jip-registry.dkfz.de/chartrepo/kaapana-public
---