---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-console-deployment
  namespace: {{ .Values.global.store_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: minio-console
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app-name: minio-console
    spec:
      initContainers:
        - name: init
          image: {{  .Values.global.registry_url }}/service_checker:1.1
          imagePullPolicy: {{ .Values.global.pull_policy_pods }}
          env:
            - name: WAIT
              value: "keycloak,keycloak-internal-service.kube-system.svc,443;minio,minio-service.store.svc,9000"
            - name: DELAY
              value: "3"
            - name: TIMEOUT
              value: "10"
      containers:
      - name: minio-console
        image: {{  .Values.global.registry_url }}/minio-console:0.15.6
        imagePullPolicy: {{ .Values.global.pull_policy_pods }}
        args: ["server", "--host", "0.0.0.0", "--port", "9001"]
        env:
        - name: KAAPANA_ADDRESS
          value: "https://{{ .Values.global.hostname }}:{{ .Values.global.https_port }}"
        - name: CONSOLE_SUBPATH
          value: /minio-console/
        - name: CONSOLE_MINIO_SERVER
          value: http://minio-service.store.svc:9000
        - name: CONSOLE_IDP_URL
          value: "http://keycloak-external-service.kube-system.svc:80/auth/realms/kaapana/.well-known/openid-configuration"
        - name: CONSOLE_IDP_CLIENT_ID
          value: "kaapana"
        - name: CONSOLE_IDP_SECRET
          value: "uQBJzc2YDzjRfj2OCT79JDShojeqAK2R"
        - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
          value: "policy"
        - name: CONSOLE_IDP_CALLBACK # has to be set as allowed redirect urls in keyloak https://{{ .Values.global.hostname }}:{{ .Values.global.https_port }}/minio-console/oauth_callback/
          value: "https://{{ .Values.global.hostname }}:{{ .Values.global.https_port }}/minio-console/oauth_callback/"
        - name: CONSOLE_SECURE_FRAME_DENY
          value: "off"
        ports:
        - name: minio-console
          containerPort: 9001
        resources:
          requests:
            memory: 200Mi
          limits:
            memory: 1000Mi
      imagePullSecrets:
      - name: registry-secret
---