---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-data-api
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  stripPrefix:
    prefixes:
    - /data-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-api-ingress
  namespace: "{{ .Values.global.services_namespace }}"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: {{  .Values.global.services_namespace  }}-strip-prefix-data-api@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /data-api
        pathType: Prefix
        backend:
          service:
            name: data-api
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: data-api
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  selector:
    app.kubernetes.io/name: data-api
    app.kubernetes.io/component: api
  ports:
    - port: 80
      targetPort: 8080