
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-meta-service
  namespace: {{ .Values.global.meta_namespace }}
  labels:
    app-name: kibana-meta
spec:
  selector:
    app-name: kibana-meta
  ports:
  - name: kibana-port
    port: 5601
    targetPort: 5601
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-meta-ingress-ip
  namespace: {{ .Values.global.meta_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd,kube-system-strip-prefix@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /meta
        backend:
          serviceName: kibana-meta-service
          servicePort: 5601
---