---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-pages
  namespace: "{{  .Values.global.system_namespace  }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: error-pages
  template:
    metadata:
      labels:
        app-name: error-pages
    spec:
      containers:
      - name: error-pages-container
        image: "{{ .Values.global.registry_url }}/error-pages:{{ .Values.global.kaapana_build_version  }}"
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        resources:
          requests:
            memory: 20Mi
          limits:
            memory: 30Mi
        ports:
        - name: http-port
          containerPort: 5000
      imagePullSecrets:
      - name: registry-secret
---
