---
global:
  dev_files: "/home/h443o/Projects/kaapana-1/services/base/workflow-api/docker/files"

kaapana_database:
  admin: false
  postgres_user: kaapanauser
  postgres_password: kaapanapassword
  postgres_db: kaapanauser
  appName: workflow-api
