---
global:
  pathPrefix: /workflow-api
  dev_files: /home/m395c/kaapana/services/base/workflow-api/docker/files

kaapana_database:
  admin: false
  postgres_user: kaapanauser
  postgres_password: kaapanapassword
  postgres_db: kaapanauser
  appName: workflow-api
