---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-api-redis
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: workflow-api-redis
      app.kubernetes.io/component: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: workflow-api-redis
        app.kubernetes.io/component: api
    spec:
      containers:
      - name: workflow-api-redis
        image:  "{{ .Values.global.registry_url }}/workflow-api-redis:{{ .Values.global.kaapana_build_version  }}"
        imagePullPolicy:  {{ .Values.global.pull_policy_images }}
        ports:
          - containerPort: 6379
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "10Mi"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true     
      imagePullSecrets:
        - name: registry-secret
