---
apiVersion: v1
kind: Service
metadata:
  name: workflow-api-redis-service
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  selector:
    app.kubernetes.io/name: workflow-api-redis
    app.kubernetes.io/component: api
  ports:
    - port: 6379