---
global:
  pull_policy_images: "IfNotPresent"
  meta_namespace: "meta"
  fast_data_dir: /home/kaapana
  dynamicVolumes:
  - name: opensearch
    host_path: /os
  - name: os-certs
    host_path: /os/certs