---
global:
  pull_policy_images: "IfNotPresent"
  meta_namespace: "meta"
  fast_data_dir: /home/kaapana
  dynamicVolumes:
  - name: os-logs
    host_path: /os/logs
  - name: os-data
    host_path: /os/data
  - name: os-certs
    host_path: /os/certs
  - name: os-security-backup
    host_path: /os/security-backup
  - name: os-snapshots
    host_path: /os/snapshots