global:
  base_namespace: "placeholder"
  credentials_registry_username: "placeholder"
  credentials_registry_password: "placeholder"
  credentials_minio_username: "placeholder"
  credentials_minio_password: "placeholder"
  credentials_grafana_username: "placeholder"
  credentials_grafana_password: "placeholder"
  credentials_keycloak_admin_username: "placeholder"
  credentials_keycloak_admin_password: "placeholder"
  dicom_port: "placeholder"
  fast_data_dir: "placeholder"
  services_namespace: "placeholder"
  extensions_namespace: "placeholder"
  admin_namespace: "placeholder"
  gpu_support: false
  helm_namespace: "placeholder"
  enable_nfs: false
  oidc_client_secret: "placeholder"
  include_reverse_proxy: false
  home_dir: "placeholder"
  hostname: "placeholder"
  http_port: "placeholder"
  https_port: "placeholder"
  internalCidrs: ["0.0.0.0/0"]
  offline_mode: false
  prefetch_extensions: false
  pull_policy_images: "Always"
  pull_policy_jobs: "Always"
  pull_policy_pods: "Always"
  registry_url: "placeholder"
  release_name: "placeholder"
  deployment_timestamp: "placeholder"
  mount_points_to_monitor: "placeholder"
  slow_data_dir: "placeholder"
  instance_uid: "placeholder"
  instance_name: "placeholder"
  dev_mode: false
  kaapana_init_password: "placeholder"
  pacs_memory_limit: "placeholder"
  airflow_memory_limit: "placeholder"
  opensearch_memory_limit: "placeholder"
  pacs_memory_request: "placeholder"
  airflow_memory_request: "placeholder"
  opensearch_memory_request: "placeholder"
  smtp_host: "placeholder"
  smtp_port: "placeholder"
  smtp_username: "placeholder"
  smtp_password: "placeholder"
  email_address_sender: "placeholder"

squid-proxy:
  upstreamHttpProxy: "placeholder"
  upstreamHttpsProxy: "placeholder"
