# default_container_registry: "dktk-jip-registry.dkfz.de"
# default_container_project: "kaapana" 
http_proxy: ""
default_container_registry: ""
default_container_project: "" 
default_chart_registry: "https://dktk-jip-registry.dkfz.de/chartrepo/"
default_chart_project: "kaapana-public"
log_level: "WARN"
build_containers: true
push_containers: true
build_charts: false
push_charts: false
create_package: false
