---
global:
  registry_url: ""
  pull_policy_images: ""
  base_namespace: ""
  namespace: "{{ .Values.global.services_namespace }}"
  dynamicVolumes:
  - name: minio
    mount_path: /minio
  collabora_username: admin
  collabora_password: admin
  collabora_prefix: /collabora
  links:
    - /web/store/Documents