---
apiVersion: v1
kind: Service
metadata:
  name: elastic-meta-service
  namespace: {{ .Values.global.meta_namespace }}
  labels:
    app-name: elastic-meta
spec:
  selector:
    app-name: elastic-meta
  type: ClusterIP
  ports:
  - name: elastic-rest
    port: 9200
    targetPort: 9200
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-ingress
  namespace: {{ .Values.global.meta_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd,kube-system-strip-prefix@kubernetescrd
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /elasticsearch
        pathType: Prefix
        backend:
          service:
            name: elastic-meta-service
            port:
              name: elastic-rest
---