
apiVersion: batch/v1
kind: Job
metadata:
  name: get-pretrained-models
  namespace: "{{ .Values.global.services_namespace }}"
spec:
  template:
    metadata:
      name: get-pretrained-models
      labels:
        network-access-external-ips: "true"
    spec:
      # hostNetwork: true
      containers:
      - name: get-pretrained-models
        image: "{{ .Values.global.registry_url }}/{ .Values.global.image}:{{ .Values.global.kaapana_build_version  }}"
        imagePullPolicy:  {{ .Values.global.pull_policy_jobs }}
        env:
        - name: MODEL_DIR
          value: "/models/total_segmentator/nnUNet"
        - name: LOG_LEVEL
          value: "INFO"
        - name: TASK_IDS
          value: {{ .Values.global.task_ids | default "total" }}
{{- if .Values.global.http_proxy }}
        - name: http_proxy
          value: {{ .Values.global.http_proxy }}
{{- end }}
{{- if .Values.global.https_proxy }}
        - name: https_proxy
          value: {{ .Values.global.https_proxy }}
{{- end }}
        volumeMounts:
        - name: modeldata
          mountPath: /models
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 6Gi
      volumes:
      - name: modeldata
        persistentVolumeClaim:
          claimName: models-pv-claim
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret
  backoffLimit: 0
